# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [1]:
import numpy as np
import collections

In [2]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  ##############################################
  ############ YOUR CODES GO HERE ##############
  matrix = np.random.randint(low=n , high=n+100, size=(n, n))

  ##############################################

  return matrix

In [8]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
##############################################
############ YOUR CODES GO HERE ##############

matrix = create_matrix(3)
print(matrix)
##############################################

[[ 56  56   8]
 [ 23  85  74]
 [ 87 100  81]]


In [4]:

def return_digits(number):
  list_of_digits = [int(i) for i in str(number)]
  return list_of_digits



def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
 
   """
  list_of_all_digits = []
  for x in np.nditer(matrix):
    list_of_all_digits = return_digits(x) + list_of_all_digits

  counter = collections.Counter(list_of_all_digits)

  ##############################################
  ############ YOUR CODES GO HERE ##############
  digits = counter
  dictionary1 = sorted(digits)
  sorted_dict = {key:digits[key] for key in dictionary1}
  ##############################################

  return sorted_dict


In [5]:
"""
In this cell call the implemented function and print the result
"""
print(count_digits(matrix))

##############################################
############ YOUR CODES GO HERE ##############
##############################################

{0: 2, 1: 2, 2: 2, 4: 2, 5: 2, 6: 4, 7: 1, 8: 2, 9: 1}


## Part B

In [6]:
def traverse_matrix(matrix):
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """
  
  new_matrix = matrix.copy() 
  size = matrix.shape[0]
  for i in range(size): 
    i= i+1
    submatrix = new_matrix[:i , :i]
    if(i%2 == 0): 
      for item in np.fliplr(submatrix).diagonal(): print(item , end =" ")
    
    else: 
      for item in np.flipud(submatrix).diagonal() : print(item , end =" ")
     

  for i in range(size): 
    submatrix = new_matrix[i+1:size , i+1:size]
    if(i%2 == 0): 
      for item in np.fliplr(submatrix).diagonal(): print(item , end =" ")
    
    else: 
      for item in np.flipud(submatrix).diagonal() : print(item , end =" ")
     



  

  ##############################################
  ############ YOUR CODES GO HERE ##############
  ##############################################

In [7]:
print(traverse_matrix(matrix))
#print output

62 10 48 56 60 97 14 26 58 None
