# Q4

## Part A

In [2]:
import numpy as np
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""
matris_A = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
matris_B = np.array([[1] , [-1] , [1]])

matris_A_transpose = np.transpose(matris_A)

x1 = np.linalg.inv(np.dot( matris_A_transpose , matris_A ))
x2 = np.dot(matris_A_transpose , matris_B)
result = np.dot(x1 , x2) + matris_A
print(result)


[[0.78125  1.78125  2.78125 ]
 [4.       5.       6.      ]
 [7.171875 8.171875 9.171875]]


## Part B

In [13]:
def window_sliding(A, B):

  w1 , h1 = B.shape; 
  w2, h2 = A.shape; 
 

  result = np.zeros((w2, h2))
  for i in range(w1): 
    for j in range(h1): 
      x = True
      sum = 0
      for k in range(w2): 
        for t in range(h2):
          if(i+k <w1 and j + t < h1):
            sum += B[i+k, j+t]* A[k,t]
          else:
            x = False
      if(x):
        result[i , j]= sum
      
    
      
  return result

In [14]:
A = np.array([[1,1,1] , [1, -9 , 1] , [1,1,1]])
B = np.array([[1,1,1,1,1], [1,2,2,2,1], [1,2,2,2,1] , [1,2,2,2,1] , [1,1,1,1,1]])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
